// Mock data for dashboard

export const patients = [
  {
    id: 'P001',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1 (555) 123-4567',
    age: 32,
    lastVisit: '2024-05-15',
    status: 'Active',
    insurance: 'Blue Shield',
  },
  {
    id: 'P002',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1 (555) 234-5678',
    age: 28,
    lastVisit: '2024-05-10',
    status: 'Active',
    insurance: 'Aetna',
  },
  {
    id: 'P003',
    name: 'Michael Brown',
    email: 'mbrown@email.com',
    phone: '+1 (555) 345-6789',
    age: 45,
    lastVisit: '2024-04-20',
    status: 'Inactive',
    insurance: 'Cigna',
  },
  {
    id: 'P004',
    name: 'Emily Davis',
    email: 'emily.davis@email.com',
    phone: '+1 (555) 456-7890',
    age: 36,
    lastVisit: '2024-05-18',
    status: 'Active',
    insurance: 'Delta Dental',
  },
  {
    id: 'P005',
    name: 'David Wilson',
    email: 'dwilson@email.com',
    phone: '+1 (555) 567-8901',
    age: 52,
    lastVisit: '2024-03-10',
    status: 'Inactive',
    insurance: 'MetLife',
  },
]

export const appointments = [
  {
    id: 'A001',
    patientId: 'P001',
    patientName: 'John Smith',
    date: '2024-06-05',
    time: '09:00 AM',
    dentist: 'Dr. Robert Chen',
    type: 'Cleaning',
    status: 'Confirmed',
    notes: 'Regular checkup',
  },
  {
    id: 'A002',
    patientId: 'P002',
    patientName: 'Sarah Johnson',
    date: '2024-06-05',
    time: '10:30 AM',
    dentist: 'Dr. Lisa Anderson',
    type: 'Filling',
    status: 'Scheduled',
    notes: 'Cavity in tooth #14',
  },
  {
    id: 'A003',
    patientId: 'P004',
    patientName: 'Emily Davis',
    date: '2024-06-05',
    time: '02:00 PM',
    dentist: 'Dr. Robert Chen',
    type: 'Root Canal',
    status: 'Confirmed',
    notes: 'Follow-up treatment',
  },
  {
    id: 'A004',
    patientId: 'P003',
    patientName: 'Michael Brown',
    date: '2024-06-06',
    time: '11:00 AM',
    dentist: 'Dr. Sarah Martinez',
    type: 'Crown',
    status: 'Scheduled',
    notes: 'Crown placement',
  },
  {
    id: 'A005',
    patientId: 'P005',
    patientName: 'David Wilson',
    date: '2024-06-07',
    time: '03:30 PM',
    dentist: 'Dr. Lisa Anderson',
    type: 'Extraction',
    status: 'Scheduled',
    notes: 'Tooth extraction #28',
  },
]

export const treatments = [
  {
    id: 'T001',
    patientId: 'P001',
    patientName: 'John Smith',
    type: 'Cleaning',
    date: '2024-05-15',
    dentist: 'Dr. Robert Chen',
    cost: 120,
    notes: 'Routine cleaning and scaling',
    status: 'Completed',
  },
  {
    id: 'T002',
    patientId: 'P002',
    patientName: 'Sarah Johnson',
    type: 'Filling',
    date: '2024-05-10',
    dentist: 'Dr. Lisa Anderson',
    cost: 250,
    notes: 'Composite filling on tooth #14',
    status: 'Completed',
  },
  {
    id: 'T003',
    patientId: 'P004',
    patientName: 'Emily Davis',
    type: 'Root Canal',
    date: '2024-04-25',
    dentist: 'Dr. Robert Chen',
    cost: 800,
    notes: 'Root canal treatment on tooth #11',
    status: 'Completed',
  },
  {
    id: 'T004',
    patientId: 'P003',
    patientName: 'Michael Brown',
    type: 'Crown',
    date: '2024-04-20',
    dentist: 'Dr. Sarah Martinez',
    cost: 1200,
    notes: 'Porcelain crown on tooth #16',
    status: 'In Progress',
  },
  {
    id: 'T005',
    patientId: 'P001',
    patientName: 'John Smith',
    type: 'Whitening',
    date: '2024-05-15',
    dentist: 'Dr. Robert Chen',
    cost: 300,
    notes: 'Professional teeth whitening',
    status: 'Completed',
  },
]

export const invoices = [
  {
    id: 'INV001',
    patientId: 'P001',
    patientName: 'John Smith',
    amount: 420,
    date: '2024-05-15',
    dueDate: '2024-06-15',
    status: 'Paid',
    items: [
      { description: 'Cleaning', amount: 120 },
      { description: 'Whitening', amount: 300 },
    ],
  },
  {
    id: 'INV002',
    patientId: 'P002',
    patientName: 'Sarah Johnson',
    amount: 250,
    date: '2024-05-10',
    dueDate: '2024-06-10',
    status: 'Pending',
    items: [{ description: 'Filling', amount: 250 }],
  },
  {
    id: 'INV003',
    patientId: 'P004',
    patientName: 'Emily Davis',
    amount: 800,
    date: '2024-04-25',
    dueDate: '2024-05-25',
    status: 'Overdue',
    items: [{ description: 'Root Canal', amount: 800 }],
  },
  {
    id: 'INV004',
    patientId: 'P003',
    patientName: 'Michael Brown',
    amount: 1200,
    date: '2024-04-20',
    dueDate: '2024-05-20',
    status: 'Partial',
    items: [{ description: 'Crown', amount: 1200 }],
  },
  {
    id: 'INV005',
    patientId: 'P005',
    patientName: 'David Wilson',
    amount: 350,
    date: '2024-03-10',
    dueDate: '2024-04-10',
    status: 'Overdue',
    items: [{ description: 'Consultation and X-ray', amount: 350 }],
  },
]

export const revenueData = [
  { month: 'Jan', revenue: 4200 },
  { month: 'Feb', revenue: 3800 },
  { month: 'Mar', revenue: 4600 },
  { month: 'Apr', revenue: 5200 },
  { month: 'May', revenue: 4900 },
  { month: 'Jun', revenue: 5800 },
]

export const appointmentStats = [
  { name: 'Completed', value: 42 },
  { name: 'Scheduled', value: 18 },
  { name: 'Cancelled', value: 5 },
  { name: 'No Show', value: 3 },
]

export const treatmentDistribution = [
  { name: 'Cleaning', value: 28 },
  { name: 'Filling', value: 15 },
  { name: 'Root Canal', value: 8 },
  { name: 'Crown', value: 12 },
  { name: 'Extraction', value: 7 },
]

export const inventory = [
  {
    id: 'INV-001',
    name: 'Composite Resin (Shade A1)',
    quantity: 45,
    unit: 'syringes',
    reorderLevel: 20,
    supplier: 'Dental Supplies Plus',
    cost: 12.50,
  },
  {
    id: 'INV-002',
    name: 'Surgical Gloves (Size L)',
    quantity: 8,
    unit: 'boxes',
    reorderLevel: 10,
    supplier: 'MedSupply Co',
    cost: 24.99,
  },
  {
    id: 'INV-003',
    name: 'Dental Bibs',
    quantity: 35,
    unit: 'boxes',
    reorderLevel: 15,
    supplier: 'ProDental',
    cost: 8.75,
  },
  {
    id: 'INV-004',
    name: 'Anesthetic Cartridge (2% Lidocaine)',
    quantity: 12,
    unit: 'boxes',
    reorderLevel: 15,
    supplier: 'Dental Supplies Plus',
    cost: 45.00,
  },
  {
    id: 'INV-005',
    name: 'Rotary Instruments Burs',
    quantity: 22,
    unit: 'sets',
    reorderLevel: 10,
    supplier: 'MedSupply Co',
    cost: 55.00,
  },
  {
    id: 'INV-006',
    name: 'Dental Suction Tips',
    quantity: 5,
    unit: 'boxes',
    reorderLevel: 8,
    supplier: 'ProDental',
    cost: 18.50,
  },
]

export const staff = [
  {
    id: 'S001',
    name: 'Dr. Robert Chen',
    role: 'Dentist',
    email: 'r.chen@dentalcare.com',
    phone: '+1 (555) 111-2222',
    specialization: 'General Dentistry',
    status: 'Active',
  },
  {
    id: 'S002',
    name: 'Dr. Lisa Anderson',
    role: 'Dentist',
    email: 'l.anderson@dentalcare.com',
    phone: '+1 (555) 222-3333',
    specialization: 'Endodontics',
    status: 'Active',
  },
  {
    id: 'S003',
    name: 'Dr. Sarah Martinez',
    role: 'Dentist',
    email: 's.martinez@dentalcare.com',
    phone: '+1 (555) 333-4444',
    specialization: 'Prosthodontics',
    status: 'Active',
  },
  {
    id: 'S004',
    name: 'Jennifer Lee',
    role: 'Receptionist',
    email: 'j.lee@dentalcare.com',
    phone: '+1 (555) 444-5555',
    specialization: 'Front Desk',
    status: 'Active',
  },
  {
    id: 'S005',
    name: 'Maria Garcia',
    role: 'Hygienist',
    email: 'm.garcia@dentalcare.com',
    phone: '+1 (555) 555-6666',
    specialization: 'Dental Hygiene',
    status: 'Active',
  },
]

export const dashboardStats = [
  {
    title: 'Total Patients',
    value: '248',
    increase: '+12%',
    icon: 'Users',
  },
  {
    title: "Today's Appointments",
    value: '8',
    increase: '+2 from yesterday',
    icon: 'Calendar',
  },
  {
    title: 'Monthly Revenue',
    value: '$24,850',
    increase: '+8.2%',
    icon: 'DollarSign',
  },
  {
    title: 'Pending Payments',
    value: '$3,450',
    increase: '5 invoices',
    icon: 'AlertCircle',
  },
  {
    title: 'Active Staff',
    value: '8',
    increase: 'All online',
    icon: 'Users2',
  },
  {
    title: 'Low Stock Items',
    value: '2',
    increase: 'Requires attention',
    icon: 'AlertTriangle',
  },
]
